require("plugins.configs.treesitter")
require("plugins.configs.autoclose")
-- require("plugins.configs.neo-tree")
require("plugins.configs.lsp_config")
-- require("plugins.configs.toggleterm")
require("plugins.configs.transparent")
-- require("plugins.configs.bufferline")
require("plugins.configs.gitsigns")
require("plugins.configs.nvim-cmp")
require("plugins.configs.telescope_conf")
require("plugins.configs.lualine")
require("plugins.configs.harpoon")
require("plugins.configs.oil")
