# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME

# hide titlebar
hide_window_decorations titlebar-only
map super+left_mouse_drag move_window

# add padding to window borders
window_padding_width 12

# transparent background
background_opacity 0.73

# Font
font_family        FiraCode Nerd Font
