# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME

font_family FiraCode Nerd Font
font_size        12.0

window_padding_width 20 20 20 20
window_border_width 20

hide_window_decorations titlebar-only

# for nvim option key to work in shortcuts
macos_option_as_alt left
map option + meta 

background_opacity 0.25
background_blur 30
background #000000

placement_strategy center
active_border_color #00ff00
